export const INSTRUCTOR_PROFILE_SEED = {
  "INS-101": {
    mainExpertise: "React.js، Next.js، TypeScript و طراحی معماری مقیاس‌پذیر",
    teachingStyle:
      "سبک تدریس او عمیق، پروژه‌محور و نزدیک به شرایط واقعی شرکت‌هاست؛ هر مبحث با سناریوی واقعی، تمرین لایه‌لایه و بازخورد مهندسی جمع‌بندی می‌شود.",
    professionalBackground:
      "او سابقه همکاری با تیم‌های محصول در حوزه‌های فین‌تک، آموزش آنلاین و SaaS را دارد و روی طراحی معماری فرانت، performance، SSR و DX تیمی تمرکز می‌کند.",
    verified: true,
    coverImage: "/images/hero_image.jpg",
    yearsOfExperience: 9,
    skills: ["JavaScript", "TypeScript", "React.js", "Next.js", "Node.js", "UI Architecture", "Performance", "Git"],
    experiences: [
      {
        type: "work",
        title: "لید فرانت‌اند",
        organization: "اسنپ",
        startDate: "۱۴۰۱",
        endDate: "اکنون",
        description: "هدایت توسعه پنل‌های عملیاتی، بازطراحی design system و بهینه‌سازی عملکرد در پروژه‌های پرترافیک.",
      },
      {
        type: "teaching",
        title: "مدرس بوت‌کمپ فرانت‌اند",
        organization: "اسپاتی‌کد",
        startDate: "۱۴۰۰",
        endDate: "اکنون",
        description: "آموزش پروژه‌محور React، Next.js و TypeScript به همراه منتورینگ فردی برای ورود به بازار کار.",
      },
    ],
    certificates: [
      { title: "Advanced React Architecture", issuer: "Frontend Masters", date: "۲۰۲۴", link: "https://frontendmasters.com" },
      { title: "Performance for Web Apps", issuer: "Google", date: "۲۰۲۳" },
    ],
    projects: [
      {
        title: "داشبورد تحلیل عملکرد فروش",
        description: "طراحی و پیاده‌سازی داشبورد مدیریتی با فیلترهای زنده و نمودارهای تحلیلی.",
        technologies: ["Next.js", "TypeScript", "Recharts", "Tailwind"],
        githubUrl: "https://github.com/arezaei/sales-dashboard",
        liveUrl: "https://demo.spoticode.ir/sales-dashboard",
        image: "/images/course3.jpg",
      },
    ],
    reviews: [
      {
        studentName: "مهدی امینی",
        rating: 5,
        reviewText: "شیوه تدریس استاد رضایی کاملاً پروژه‌محور است و دقیقاً حس کار در تیم واقعی را منتقل می‌کند.",
        relatedCourse: "متخصص React و Next.js",
        date: "اردیبهشت ۱۴۰۵",
      },
    ],
    socials: {
      github: "https://github.com/arezaei",
      linkedin: "https://linkedin.com/in/arezaei",
      telegram: "https://t.me/arezaei_dev",
      website: "https://rezaei.dev",
      email: "amirreza@spoticode.ir",
      phone: "۰۹۱۲۳۴۵۶۷۸۹",
    },
    publicVisibility: { email: true, phone: false },
  },
  "INS-102": {
    mainExpertise: "React، State Management، Design Systems",
    teachingStyle: "رویکرد او بر یادگیری مرحله‌ای، ساخت پروژه‌های قابل ارائه و توضیح چرایی تصمیم‌های فنی استوار است.",
    professionalBackground:
      "او سابقه کار روی پنل‌های تحلیلی، اپلیکیشن‌های مدیریت مشتری و سامانه‌های آموزشی را در نقش frontend engineer دارد.",
    verified: true,
    yearsOfExperience: 7,
    skills: ["React.js", "SWR", "Design Systems", "Accessibility", "Tailwind CSS", "Testing"],
    experiences: [
      {
        type: "work",
        title: "Senior Frontend Engineer",
        organization: "پلتفرم مدیریت مشتری",
        startDate: "۱۴۰۰",
        endDate: "اکنون",
        description: "توسعه رابط‌های داده‌محور و کامپوننت‌های reusable برای محصول سازمانی.",
      },
    ],
    projects: [
      {
        title: "کتابخانه Design System داخلی",
        description: "مجموعه‌ای از کامپوننت‌های استاندارد برای محصولات سازمانی.",
        technologies: ["React", "Storybook", "TypeScript"],
        githubUrl: "https://github.com/mheidari/design-system",
      },
    ],
    socials: {
      github: "https://github.com/mheidari",
      linkedin: "https://linkedin.com/in/mheidari",
      telegram: "https://t.me/mheidari_ui",
    },
    publicVisibility: { email: false, phone: false },
  },
  "INS-103": {
    mainExpertise: "CSS، طراحی واکنش‌گرا، Flexbox، Grid و سیستم‌های طراحی",
    verified: true,
    yearsOfExperience: 6,
    skills: ["CSS", "Responsive Design", "Flexbox", "Grid", "UI/UX", "Figma"],
    experiences: [
      {
        type: "work",
        title: "UI Engineer",
        organization: "استودیو طراحی محصول",
        startDate: "۱۳۹۹",
        endDate: "اکنون",
        description: "توسعه رابط‌های بصری و responsive برای محصولات وب.",
      },
    ],
    socials: {
      linkedin: "https://linkedin.com/in/saramohammadi",
      website: "https://saramohammadi.design",
    },
    publicVisibility: { email: false, phone: false },
  },
  "INS-104": {
    mainExpertise: "HTML، ساختار وب، فرم‌ها و استانداردهای دسترس‌پذیری",
    verified: true,
    yearsOfExperience: 5,
    skills: ["HTML", "Semantic Markup", "Accessibility", "Forms", "SEO Basics"],
    experiences: [
      {
        type: "teaching",
        title: "مدرس مبانی وب",
        organization: "اسپاتی‌کد",
        startDate: "۱۴۰۱",
        endDate: "اکنون",
        description: "طراحی مسیر یادگیری پایه برای ورود هنرجویان به فرانت‌اند.",
      },
    ],
    socials: {
      github: "https://github.com/nalavi",
      telegram: "https://t.me/nima_web",
    },
    publicVisibility: { email: false, phone: false },
  },
} as const;

export const COMMENT_SEED = [
  {
    id: "comment-nextjs-1",
    courseId: "nextjs",
    content: "پروژه‌های عملی این دوره باعث شد ترس من از کدنویسی بریزه. محتوا بسیار کاربردی و به‌روز است.",
    rating: 5,
    authorId: "user-1",
    authorName: "سهراب امینی",
    authorRole: "توسعه‌دهنده React",
    authorAvatar: "/images/student1.jpg",
    createdAt: new Date("2026-05-12T09:00:00.000Z"),
  },
  {
    id: "comment-nextjs-2",
    courseId: "nextjs",
    content: "بهترین تصمیمی که برای آینده‌ام گرفتم شرکت در این دوره بود. منتورها واقعاً دلسوزانه کمک می‌کنند.",
    rating: 5,
    authorId: "user-2",
    authorName: "سارا رضایی",
    authorRole: "توسعه‌دهنده فرانت‌اند",
    authorAvatar: "/images/student2.jpg",
    createdAt: new Date("2026-05-02T09:00:00.000Z"),
  },
  {
    id: "comment-nextjs-2-reply",
    courseId: "nextjs",
    parentId: "comment-nextjs-2",
    content: "خوشحالیم که تجربه خوبی داشتید. موفق باشید!",
    authorName: "امیررضا رضایی",
    authorRole: "مدرس",
    authorAvatar: "/images/inst1.jpg",
    isInstructorReply: true,
    createdAt: new Date("2026-05-10T09:00:00.000Z"),
  },
  {
    id: "comment-nextjs-3",
    courseId: "nextjs",
    content: "محتوای آموزشی بسیار به‌روز و با کیفیت هست. پشتیبانی ۲۴ ساعته واقعاً یک مزیت بزرگه.",
    rating: 4,
    authorId: "user-3",
    authorName: "نیما حسینی",
    authorRole: "متخصص دیتاساینس",
    authorAvatar: "/images/student3.jpg",
    createdAt: new Date("2026-04-19T09:00:00.000Z"),
  },
  {
    id: "comment-react-1",
    courseId: "react",
    content: "هوک‌ها و state management خیلی خوب توضیح داده شد.",
    rating: 5,
    authorId: "user-4",
    authorName: "نگار کریمی",
    authorRole: "دانشجو",
    authorAvatar: "/images/student1.jpg",
    createdAt: new Date("2026-05-16T11:30:00.000Z"),
  },
  {
    id: "comment-js-1",
    courseId: "javascript",
    content: "از صفر تا Fetch API عالی پیش رفت. برای شروع عالیه.",
    rating: 5,
    authorId: "user-5",
    authorName: "علی مرادی",
    authorRole: "دانشجو",
    authorAvatar: "/images/student2.jpg",
    createdAt: new Date("2026-05-18T10:10:00.000Z"),
  },
] as const;
